spring:
  application:
    name: hystrix-dashboard-turbine
  profiles:
    active:
    - '@profileActive@'

server:
  port: 8001

turbine:
#  aggregator:
#    clusterConfig: service-user
  appConfig: service-user
#  instanceUrlSuffix:
#    default: /spring-manager/hystrix.stream
  clusterNameExpression: "'default'"
