spring:
  application:
    name: hystrix-dashboard-turbine
server:
  port: 8001

turbine:
#  aggregator:
#    clusterConfig: service-user
  appConfig: service-user
#  instanceUrlSuffix:
#    service-user: /spring-manager/hystrix.stream
  clusterNameExpression: new String("default")
