eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.52.124:8888/eureka

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.39:3306/jiguang
    username: root
    password: root

