# Configure this Discovery Server
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.52.124:8888/eureka/
  server:
    enable-self-preservation: false
