eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka

spring:
  zipkin:
    base-url: http://localhost:8002
  thymeleaf:
    cache: false

jiguang:
  config:
    outputExceptionStackTrace: true
